### ISSUE TITLE
iGlance crashes when you try to look at Disk Window

### ISSUE THREAD

**Issue by clintonblackmore** [iglance/iGlance#189] opened 2020-06-11 15:05 UTC
**Describe the bug🐛**
When you bring up the iGlance window and click on "Disk" it crashes.

**To Reproduce**
Steps to reproduce the behaviour:

1. Start iGlance.
2. Click on one of the widgets and choose "Show Window"
3. These are different areas to set settings for, such as "Dashboard", "CPU", "Memory", etc.
4. Note that you can click on most of these without issue.
5. When you click on "Disk", the application immediately crashes.

**Expected behaviour**
I should be able to see the graphing settings for the disk, and adjust them.

**Screenshots (Optional)**
N/A

**Desktop (please complete the following information):**

- MacOS version: 10.14.6 (build 18G4032)
- Version of the app: 2.0.8

**Log**
[io.github.iglance.iGlance 2020-06-11--15-02-10-409.log](https://github.com/iglance/iGlance/files/4765636/io.github.iglance.iGlance.2020-06-11--15-02-10-409.log)

**Comment by D0miH** [comment] 2020-06-17 17:13
Hey @clintonblackmore,
thanks for reporting the issue. Unfortunately I can't reproduce the bug on my machine. Are you sure that the latest version is installed? This issue was present once in version  2.0.8 but was quickly fixed within an hour. The app download was changed to include a fixed version of the app. However the hot-fix was still published under version 2.0.8.
So please try to re-download the app and test if the issue is still appearing.

**Comment by clintonblackmore** [comment] 2020-06-17 17:34
Hey, that fixed it. 

Thank you.

**Closed** 2020-06-17 17:34 UTC
