### ISSUE TITLE
Invisible/transparent icons in menu bar

### ISSUE THREAD

**Issue by ibead** [iglance/iGlance#183] opened 2020-05-23 06:55 UTC
The iGlance topbar icons only appear on either my MBP screen, or on my external monitor after restarting my system. On the screen where they do not appear, the cpu and memory level meters are visible without framework. 

Install iGlance 
Make sure it restarts automatically after rebooting 
Reboot your system with an external monitor connected 

The iGlance icons / information in the topbar should be visible on external displays. 

MacOS 10.15.4

**Comment by ibead** [comment] 2020-05-23 15:40
Edit: monitor is disconnected, and still the topbar icons are not visible except for the level meters. It is possible to click on the invisible icons and get the dropdown with options.

**Comment by D0miH** [comment] 2020-05-23 17:15
Hi @ibead,
thanks for reporting this issue. I will try to reproduce the bug and get back to you soon :)

**Comment by D0miH** [comment] 2020-05-25 16:36
So I tried to reproduce the issue using the following steps:
1. Activate "Autostart on Boot"
2. Shut down the Macbook
3. Attach external display
4. Start Macbook

But I am not able to reproduce the bug on my system. All menu bar icons are visible on the internal monitor of the Macbook as well as on the external monitor. 

To further investigate the issue could you provide your logs? To do this please activate "Advanced Logging" in the iGlance settings, reproduce the issue and then export the latest log file using `Diagnostics > Save Logfile...` and upload the log file here. My guess is that something is going wrong when drawing the icons.

**Comment by ibead** [comment] 2020-05-28 21:07
Thanks for looking into it. After another restart, the icons are visible again. Perhaps it has to do with the appearance settings which I changed in the general settings. Will try to reproduce the bug again and log as suggested.

**Comment by D0miH** [comment] 2020-05-29 07:44
Glad to hear that the issue was resolved!

Closing this. If the issue reappears feel free to re-open the issue.

**Comment by ollegz** [comment] 2020-07-03 15:23
I seem to have the same problem and its consistently "disappearing" icons. I think its something with that I use Auto for appearance in general system settings as when I set it to Light/Dark they reappear.

**Comment by D0miH** [comment] 2020-07-03 16:10
Are the items are in the wrong appearance (light/dark) or are they not visible at all?

**Comment by ollegz** [comment] 2020-07-03 17:11
Transparent, when I click them I can see them. Which might mean wrong appearance yes :D

**Comment by D0miH** [comment] 2020-07-03 17:13
Ok, this should be fixable ;)
As you suggested I think this has something to do with the fact that the app does not recognize which os theme is currently active. I will look into it.

**Closed** 2020-10-04 17:38 UTC
Labels: bug
