### ISSUE TITLE
Fix MacOS Big Sur Dark/Light theme font/border color issue

### ISSUE THREAD

**Issue by MarlonJD** [iglance/iGlance#250] opened 2020-12-07 22:28 UTC
**Describe the bug🐛**
On light theme, there was an issue about the font color. On light theme black color is really bad on Big Sur.
![image](https://user-images.githubusercontent.com/8514643/101212510-e37d6f00-3689-11eb-9de7-eec7c63bf2dc.png)

**Expected behavior**
On Big Sur it has to be white on light theme

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/8514643/101212510-e37d6f00-3689-11eb-9de7-eec7c63bf2dc.png)

**Desktop (please complete the following information):**

- MacOS Version: 11.1
- Version of the app: 2.0.4

**Comment by D0miH** [comment] 2020-12-17 10:02
Hey @MarlonJD,
thanks for reporting the issue. I answered you on your PR [here](https://github.com/iglance/iGlance/pull/251#issuecomment-747337862).
Since this issue is a duplicate of #229 I will close this issue here. If you have any questions or comments please do so over at #229.

**Closed** 2020-12-17 10:02 UTC
Labels: duplicate
