### ISSUE TITLE
Network status should be for Thunderbolt LAN connection

### ISSUE THREAD

**Issue by asaduzzaman-shuvro** [iglance/iGlance#38] opened 2019-10-16 06:47 UTC
**Is your feature request related to a problem? Please describe.**
The network status showing 0 kb/s for thunderbolt lan connection.

**Describe the solution you'd like**
The network status only working with wifi connection. but this not working with LAN connection. I did't check with bluetooth. I checked with thunderbolt LAN connection. And found 0 kb/s

**Comment by D0miH** [comment] 2019-11-20 09:06
Hey @asaduzzaman-shuvro,

thanks for the feature request. This is indeed a good point and is related to #47 since you probably need to be able to select a different network interface in order to use your thunderbolt adapter.

**Comment by D0miH** [comment] 2019-12-04 10:00
closing this since it is a duplicate of #42. For further info see discussion in #42.

**Closed by D0miH** 2019-12-04 10:00 UTC
Labels: duplicate, enhancement
