### ISSUE TITLE
App won't launch in Catalina 15.2

### ISSUE THREAD

**Issue by shahnewazrifat** [iglance/iGlance#71] opened 2020-01-16 10:42 UTC
**Describe the bug**
Tried both installing manually from releases and brew cask. Double clicking the icon only flashes for a second and nothing happens.

**To Reproduce**
1. Install on Catalina 15.2
2. Double Click on iGlance.app

**Expected behavior**
App shows up
**Screenshots**
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS Catalina 15.2
 - Version of the app: 1.4.3

**Additional context**

**Comment by D0miH** [comment] 2020-01-16 10:52
Hey @shahnewazrifat,

thanks for your bug report.
I can't reproduce this problem on my machine.
Please try the following:
1. Double-click the app
2. Open "Activity Monitor" and search for "iGlance" while having selected the "CPU" tab.
Is iGlance shown in the list of running processes?

If it is shown in the list I suppose the menu bar icons are not shown and something went wrong with the default preferences. To reset your preferences open finder and while holding the option key click on "Go" > "Library". Then navigate to "Preferences" and delete all files that have "iglance" in their filename.

Hope this helps

**Comment by shahnewazrifat** [comment] 2020-01-17 05:46
Hi @D0miH ! 
Thanks for the response!

But no, it's not there in Activity Monitor (CPU Tab). :(
It just feels like when I double click - it does nothing.

**Comment by shahnewazrifat** [comment] 2020-01-17 05:46
P.S., I did allow it from privacy etc.

**Comment by D0miH** [comment] 2020-01-17 14:24
hmm this seems strange. Are there any crash logs you can upload? You can find crash logs by opening the "Console.app"-app and click on "Crash Reports" in the sidebar. If there are any crash reports of iGlance they should appear in the list.

**Comment by nadavf24** [comment] 2020-01-19 14:40
hi have just reproduced the same bug with the exact same symptoms seems to be a mac os related bug

Logs: [](https://pastebin.pl/view/bc20d8ef)

**Comment by D0miH** [comment] 2020-01-19 15:06
Hey @nadavf24,
thanks for the crash report. As far as I can see this issue is related to the initialization of the fan component of the app. 
@shahnewazrifat @nadavf24 What machines are you using? Does your machine have a fan? Or do you guys have a fan-less machine like for example the Macbook Air?

**Comment by nadavf24** [comment] 2020-01-20 09:29
it a last gen macbook fanless......

**Comment by D0miH** [comment] 2020-01-20 09:31
ok. Thanks for the detailed information:)

I will look into it. A hotfix should be released in the next few days.

**Comment by shahnewazrifat** [comment] 2020-01-20 12:42
Thanks so much @nadavf24 and @D0miH !!! really appreciate it.
It works fine on my MacBook Air (late 2013)
The problem is in a Hackintosh. I think the root cause is same - it cannot find the fan :-D 

Sorry I should have mentioned it. I thought the OS version is all that matters.

**Closed** 2020-01-20 17:07 UTC
Labels: bug

**Comment by D0miH** [comment] 2020-01-20 17:26
I just published a hotfix. Please re-download the latest release and try again:)

**Comment by shahnewazrifat** [comment] 2020-01-20 18:06
@D0miH Can't thank you enough!! Worked like a charm!

You're the best! 🎉 
And this app is simply awesome <3
